#!/bin/bash
# HTML 파일을 C 문자열 리터럴로 변환하는 스크립트

HTML_FILE="$1"
OUTPUT_FILE="$2"

if [ -z "$HTML_FILE" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: $0 <html_file> <output_header>"
    exit 1
fi

if [ ! -f "$HTML_FILE" ]; then
    echo "Error: HTML file not found: $HTML_FILE"
    exit 1
fi

echo "/* Auto-generated from $(basename $HTML_FILE) */" > "$OUTPUT_FILE"
echo "/* Do not edit this file directly */" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# HTML 파일을 읽어서 C 문자열 리터럴로 변환
# 각 줄을 따옴표로 감싸고 이스케이프 처리
awk '
BEGIN {
    # 첫 줄 시작
    first = 1
}
{
    # 백슬래시와 따옴표 이스케이프
    gsub(/\\/, "\\\\")
    gsub(/"/, "\\\"")
    
    if (first) {
        printf "\"%s\\n\"\n", $0
        first = 0
    } else {
        printf "\"%s\\n\"\n", $0
    }
}
' "$HTML_FILE" >> "$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
